import { useEffect, useState } from "react";
import { csv, json, type Row, type Summary } from "./api";
import { AnnualChart, MetricChart, NavChart, RankChart } from "./components/ResearchChart";

const path = (name: string) => `./outputs/${name}`;
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
function Stat({ label, value, note, accent = false }: { label: string; value: string; note: string; accent?: boolean }) { return <article className={`stat ${accent ? "accent" : ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function ResearchCard({ title, text }: { title: string; text: string }) { return <article className="research-card"><span className="section-kicker">研究笔记</span><h3>{title}</h3><p>{text}</p></article>; }

function Microcap() {
  const [data, setData] = useState<{ summary: Summary; annual: Row[]; nav: Row[]; cagr: Row[]; drawdown: Row[] } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([json<Summary>(path("microcap/summary.json")), csv(path("microcap/annual_returns.csv")), csv(path("microcap/nav.csv")), csv(path("microcap/rolling_cagr.csv")), csv(path("microcap/rolling_drawdown.csv"))]).then(([summary, annual, nav, cagr, drawdown]) => setData({ summary, annual, nav, cagr, drawdown })).catch((e) => setError(e.message)); }, []);
  if (error) return <p className="load-error">数据加载失败：{error}。请刷新页面或稍后再试。</p>;
  if (!data) return <p className="loading">正在加载微盘研究数据……</p>;
  const { summary, annual, nav, cagr, drawdown } = data;
  return <><header className="theme-heading"><div><span className="section-kicker">微盘规则复现研究 · {summary.source_label}</span><h2>尽量复现编制思路，也要把路径和代价画出来。</h2><p>这是基于公开资料的规则重建研究，不是 Wind 官方指数页面，也不代表实时精确复制。</p></div><span className="asof">截至 {summary.as_of}</span></header><section className="stat-grid"><Stat label="累计净值" value={summary.metrics.cumulative_nav.toFixed(2)} note="1999 年底 = 1" accent/><Stat label="2025 年收益" value={pct(summary.metrics.annual_return)} note="完整年度"/><Stat label="2026 年至今" value={pct(summary.metrics.ytd_2026_reference)} note={`参考截至 ${summary.metrics.ytd_2026_as_of}`}/><Stat label="滚动 20 年 CAGR" value={pct(summary.metrics.cagr_20y)} note="截至最新完整年度"/><Stat label="20 年月频回撤" value={pct(summary.metrics.monthly_drawdown_20y)} note="月末净值测算"/></section><div className="panel ytd-panel"><div className="panel-title"><h3>2026 年至今</h3><span className="tag warm">参考快照</span></div><p>截至 {summary.metrics.ytd_2026_as_of}，公开资料参考收益为 <strong>{pct(summary.metrics.ytd_2026_reference)}</strong>。这项数据尚未并入完整年度、累计净值和滚动指标序列。</p></div><section className="section-heading"><h3>收益路径</h3><p>少数极端年份会显著抬高长期年化，曲线需要结合回撤和持有期限阅读。</p></section><div className="panel"><div className="panel-title"><h3>累计净值</h3><span className="tag">可悬停、缩放</span></div><NavChart rows={nav}/></div><div className="panel"><div className="panel-title"><h3>年度收益</h3><span className="tag warm">悬停查看数值</span></div><AnnualChart rows={annual}/></div><div className="research-grid"><div className="panel"><div className="panel-title"><h3>滚动 CAGR</h3><span className="tag">持有期限</span></div><MetricChart rows={cagr} value="cagr" label="年化收益"/></div><div className="panel"><div className="panel-title"><h3>滚动最大回撤</h3><span className="tag warm">月频与日频参考</span></div><MetricChart rows={drawdown} value="max_drawdown" label="最大回撤"/></div></div><section className="section-heading"><h3>研究解读</h3><p>把指数规则、收益来源、历史阶段和复制难度放在同一条阅读路径上。</p></section><div className="research-grid"><ResearchCard title="两个微盘口径" text="8841431.WI 每日调仓，适合观察极小市值与再平衡机制。868008.WI 每月调仓，换手和执行压力相对更低。"/><ResearchCard title="收益来源" text="主要暴露包括极小市值、等权再平衡、短期反转和流动性风险溢价。这里是研究解释，不代表精确的因子归因。"/><ResearchCard title="历史阶段" text="2001 至 2005 年连续下跌。2006 至 2015 年多个极端上涨年份抬高长期 CAGR。2017 至 2018 年处于风格逆风期。"/><ResearchCard title="复制难度" text="小资金可以接近完整复制。规模扩大后，需要抽样、优化执行，并承担成交不足、涨跌停、停牌和冲击成本。"/></div><details className="research-note"><summary>数据边界与阅读提示</summary><ul>{summary.caveats.map((item) => <li key={item}>{item}</li>)}</ul><p>2026 年至今为公开资料参考值，未并入完整年度序列。</p></details></>;
}

function Indices() { const [data, setData] = useState<{ price: Row[]; etf: Row[] } | null>(null); const [error, setError] = useState(""); useEffect(() => { Promise.all([csv(path("linked_indices/ten_year_price_returns.csv")), csv(path("linked_indices/paired_index_etf_representatives.csv"))]).then(([price, etf]) => setData({ price, etf })).catch((e) => setError(e.message)); }, []); if (error) return <p className="load-error">数据加载失败：{error}。请刷新页面或稍后再试。</p>; if (!data) return <p className="loading">正在加载指数研究数据……</p>; const { price, etf } = data; return <><header className="theme-heading"><div><span className="section-kicker">指数长期回报 · 研究快照</span><h2>长期指数回报，先把口径说清楚。</h2><p>从价格指数到 ETF 代理结果，比较长期风格表现和真实持有结果。</p></div><span className="asof">静态快照</span></header><section className="stat-grid"><Stat label="可比指数" value={String(price.length)} note="有完整十年起止数据" accent/><Stat label="代表 ETF" value={String(etf.length)} note="通过流动性筛选"/><Stat label="最高十年年化" value={pct(Math.max(...price.map((r) => Number(r.cagr))))} note="价格回报"/></section><div className="panel"><div className="panel-title"><h3>十年价格回报排名</h3><span className="tag">悬停查看数值</span></div><RankChart rows={price}/></div><div className="panel"><div className="panel-title"><h3>代表 ETF 长期表现</h3><span className="tag warm">ETF 复权回报</span></div><MetricChart rows={etf.slice(0, 12)} value="etf_cagr" label="ETF 年化"/></div><div className="panel data-table-panel"><h3>ETF 代表明细</h3><div className="table-scroll"><table><thead><tr><th>ETF</th><th>跟踪指数</th><th>ETF 年化</th><th>指数年化</th><th>ETF 回撤</th></tr></thead><tbody>{etf.slice(0, 18).map((row) => <tr key={row.ts_code}><td>{row.ts_code} {row.name}</td><td>{row.matched_index_name}</td><td>{pct(Number(row.etf_cagr))}</td><td>{pct(Number(row.index_cagr))}</td><td>{pct(Number(row.etf_max_drawdown))}</td></tr>)}</tbody></table></div></div><details className="research-note" open><summary>指数页数据说明</summary><p>价格指数不含分红。ETF 复权价是总回报近似，仍会受到管理费、跟踪误差、汇率和交易成本影响。</p></details></>; }

export default function App() { const [tab, setTab] = useState(location.hash.slice(1) === "indices" ? "indices" : "microcap"); useEffect(() => { const on = () => setTab(location.hash.slice(1) === "indices" ? "indices" : "microcap"); addEventListener("hashchange", on); return () => removeEventListener("hashchange", on); }, []); return <div className="app"><header className="site-header"><div className="site-masthead"><div><span className="brand-kicker">Index Research · 规则化研究</span><h1>微盘股与指数研究</h1><p className="site-deck">把长期收益、风险路径和可投资性放在同一套公开快照里。</p></div><div className="site-meta"><span>研究看板</span><strong>数据优先，口径清楚</strong></div></div><nav className="site-nav" aria-label="研究主题"><a className={tab === "microcap" ? "active" : ""} href="#microcap">微盘股研究</a><a className={tab === "indices" ? "active" : ""} href="#indices">指数长期回报</a></nav></header><main className="site-main">{tab === "microcap" ? <Microcap/> : <Indices/>}</main><footer className="site-footer"><span>静态研究快照 · 仅供研究参考</span><a href="https://github.com/runchengxie/index-research">查看 GitHub 仓库 ↗</a></footer></div>; }
