import { useEffect, useRef } from "react";
import * as echarts from "echarts";
import type { Row } from "../api";

export function NavChart({ rows }:{rows:Row[]}) { return <Chart option={{tooltip:{trigger:"axis"},dataZoom:[{type:"inside"},{type:"slider",height:12,bottom:8,showDetail:false}],grid:{left:48,right:24,top:24,bottom:44},xAxis:{type:"category",data:rows.map(r=>r.date),axisLabel:{formatter:(v:string)=>v.slice(0,4),hideOverlap:true}},yAxis:{type:"value",scale:true},series:[{name:"累计净值",type:"line",showSymbol:false,smooth:true,data:rows.map(r=>Number(r.nav)),lineStyle:{width:2.5,color:"#1267d6"},areaStyle:{color:"rgba(18,103,214,.08)"}}]}} />; }
export function ReconstructedNavChart({ rows }:{rows:Row[]}) { return <Chart option={{tooltip:{trigger:"axis",formatter:(params:any)=>{const item=Array.isArray(params)?params[0]:params;return `${item.axisValue}<br/>连续净值：${Number(item.value).toFixed(3)}`}},dataZoom:[{type:"inside"},{type:"slider",height:12,bottom:8,showDetail:false}],grid:{left:48,right:24,top:24,bottom:44},xAxis:{type:"category",data:rows.map(r=>r.date),axisLabel:{formatter:(v:string)=>v.slice(0,4),hideOverlap:true}},yAxis:{type:"value",scale:true},series:[{name:"Tushare 规则重建净值",type:"line",showSymbol:false,smooth:false,data:rows.map(r=>Number(r.nav)),lineStyle:{width:2,color:"#b96800"},areaStyle:{color:"rgba(185,104,0,.08)"}}]}} />; }
export function AnnualChart({ rows }:{rows:Row[]}) { return <Chart option={{tooltip:{trigger:"axis",formatter:(params:any)=>{const item=Array.isArray(params)?params[0]:params;return `${item.axisValue}<br/>年度收益：${(Number(rows[item.dataIndex].return)*100).toFixed(2)}%`}},grid:{left:48,right:24,top:24,bottom:44},xAxis:{type:"category",data:rows.map(r=>r.year),axisLabel:{interval:2}},yAxis:{type:"value",axisLabel:{formatter:"{value}%"}},series:[{type:"bar",data:rows.map(r=>({value:Number(r.return)*100,itemStyle:{color:Number(r.return)>=0?"#1267d6":"#c53a37"}}))}]}} />; }
export function RankChart({ rows }:{rows:Row[]}) { const top=[...rows].sort((a,b)=>Number(b.cagr)-Number(a.cagr)).slice(0,12); return <Chart option={{tooltip:{trigger:"axis",axisPointer:{type:"shadow"},formatter:(params:any)=>{const item=Array.isArray(params)?params[0]:params;return `${item.name}<br/>十年年化价格回报：${Number(item.value).toFixed(1)}%`}},grid:{left:140,right:32,top:12,bottom:24},xAxis:{type:"value",axisLabel:{formatter:"{value}%"}},yAxis:{type:"category",data:top.map(r=>r.indx_name).reverse(),axisLabel:{width:120,overflow:"truncate"}},series:[{type:"bar",data:top.map(r=>Number(r.cagr)*100).reverse(),itemStyle:{color:"#1267d6"}}]}} />; }
export function MetricChart({ rows, value, label }:{rows:Row[];value:string;label:string}) { const ordered=[...rows].sort((a,b)=>Number(a.window_years)-Number(b.window_years)); return <Chart option={{tooltip:{trigger:"axis",formatter:(params:any)=>{const item=Array.isArray(params)?params[0]:params;const row=ordered[item.dataIndex];return `${row.window_years} 年 · ${row.frequency||""}<br/>${label}：${(Number(row[value])*100).toFixed(1)}%`}},grid:{left:52,right:28,top:24,bottom:44},xAxis:{type:"category",data:ordered.map(r=>`${r.window_years}年`),axisLabel:{interval:0}},yAxis:{type:"value",axisLabel:{formatter:"{value}%"}},series:[{type:"bar",data:ordered.map(r=>Number(r[value])*100),itemStyle:{color:value==="max_drawdown"?"#c53a37":"#1267d6"}}]}} />; }
export function UnderwaterChart({ rows }:{rows:Row[]}) { const top=[...rows].sort((a,b)=>Number(b.trading_days)-Number(a.trading_days)).slice(0,10); return <Chart option={{tooltip:{trigger:"axis",axisPointer:{type:"shadow"},formatter:(params:any)=>{const item=Array.isArray(params)?params[0]:params;const row=top[item.dataIndex];return `${row.start_date} 至 ${row.end_date}<br/>水下交易日：${row.trading_days}<br/>最大回撤：${(Number(row.max_drawdown)*100).toFixed(1)}%`}},grid:{left:110,right:28,top:12,bottom:24},xAxis:{type:"value",name:"交易日",nameTextStyle:{color:"#747d87"}},yAxis:{type:"category",data:top.map(r=>r.start_date).reverse(),axisLabel:{width:90}},series:[{type:"bar",data:top.map(r=>Number(r.trading_days)).reverse(),itemStyle:{color:"#b96800"}}]}} />; }
function Chart({option}:{option:echarts.EChartsOption}) { const ref=useRef<HTMLDivElement>(null); useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);chart.setOption(option);const resize=()=>chart.resize();window.addEventListener("resize",resize);return()=>{window.removeEventListener("resize",resize);chart.dispose()};},[option]); return <div ref={ref} className="research-chart" role="img" />; }
